DELETE FROM field_info;
DELETE FROM field_info_price;
DELETE FROM field_partition_price;
DELETE FROM goods_info;
DELETE FROM goods_sku_price;
DELETE FROM group_purchase;
DELETE FROM group_purchasetime;
DELETE FROM lesson_info;
DELETE FROM order_field;
DELETE FROM order_field_list;
DELETE FROM order_goods;
DELETE FROM order_goods_list;
DELETE FROM order_group_purc;
DELETE FROM order_group_purc_list;
DELETE FROM order_lesson;
DELETE FROM order_lesson_list;
DELETE FROM order_refund_info;
DELETE FROM order_service;
DELETE FROM order_service_list;
DELETE FROM order_track;
DELETE FROM service_info;
DELETE FROM sku_key;
DELETE FROM sku_value;
DELETE FROM sys_code_max;
DELETE FROM business_sales; 
INSERT INTO `sys_code_max` (`id`, `code_name`, `code_date`, `code_value`) VALUES ('001', '¶©µ¥±àºÅ',NOW(), '0');
INSERT INTO `sys_code_max` (`id`, `code_name`, `code_date`, `code_value`) VALUES ('002', 'Ä£¿é±àºÅ', NOW(), '0');
INSERT INTO `sys_code_max` (`id`, `code_name`, `code_date`, `code_value`) VALUES ('003', 'ÇøÓò±àºÅ', NOW(), '0');

delete from account;
delete from address;
delete from adver_building;
delete from adver_manage;
delete from adver_position;
delete from business_balance;
delete from business_balance_detail;
delete from business_categorydict;
delete from business_categoryinfo;
delete from business_info;
delete from business_servicescope;
delete from business_servicetime;
delete from coupon_manage;
delete from coupon_manage_users;
delete from edition_manage;
delete from group_purchase;
delete from group_purchasetime;
delete from member_discount;
delete from module_manage;
delete from my_collect;
delete from property_balance;
delete from property_balance_detail;
-- delete from property_company;
delete from recharge_manage;
delete from shopping_cart;
-- delete from company_info;
-- delete from room_certify;
-- delete from village_info;
-- delete from village_line;
-- delete from wallet_detail;
-- delete from village_linerecommodule;
-- delete from village_linerecomspecial;
